RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 256
CHUNK_OVERLAP: 32
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db'
MODEL_TYPE: 'llama'
MODEL_BIN_PATH: 'llm_gguf_model/mistral-7b-instruct-v0.2.Q4_K_M.gguf'
MAX_NEW_TOKENS: 512
TEMPERATURE: 0.2

# GPU_LAYERS: 10
GPU_LAYERS: 32
BATCH_SIZE: 32
NUM_THREADS: 4